// export const API_BASE_URL = "http://localhost:8000/api/v1/"
// export const LOGIN = "login"
export const API_BASE_URL = "https://tarian-test.com/api/v1/"
export const API_LOGIN = "session_connect/"
export const API_FORGOT_PASSWORD = "forgotpassword"
export const API_STAFF_USER_CONNECT = "StaffUserConnect"
export const API_STAFF_ORGANIZATION_LOOKUP = "StaffOrganisationLookup"
export const API_STAFF_PATIENT_FIND = "StaffPatientFind"
export const API_STAFF_PATIENT_RECORD = "StaffPatientRecord"
export const API_STAFF_USER_PHARMACY_DETAIL = "StaffUserPharmacyDetail"
export const API_STAFF_PATIENT_CONTACT_RECORD = "StaffPatientContactRecord"
export const API_STAFF_APPOINTMENT_DETAIL = "StaffAppointmentsDetails"
export const API_STAFF_GET_APPOINTMENT_SLOTS = "StaffGetAppointmentSlots"
export const API_STAFF_CREATE_BOOKING = "StaffCreateBooking"
export const API_STAFF_CANCEL_BOOKING = "StaffCancelBooking"
export const API_STAFF_MEDICAL_HISTORY = "StaffCareRecordSummaryMedicalHistory"
export const API_STAFF_CARE_RECORD_HEALTH_SUMMARY  = "StaffCareRecordHealthSummary"
export const API_STAFF_GET_STATUS_TYPE = "StaffGetStatusType"
export const API_STAFF_PATIENT_TIMELINE = "StaffPatientTimeline"
export const API_STAFF_MESSAGE_DETAIL = 'StaffMessagesDetail'
export const API_COMPOSE_MESSAGE = 'StaffCreateMessage'
export const API_CARE_RECORD_REPEAT_SUMMARY = 'StaffCareRecordRepeatsSummary'
export const API_CONFIRM_ORDER_REPEAT_PRESCRIPTION = 'StaffPrescriptionRequest'
export const API_STAFF_CARE_RECORD_CREATE_MEDICATION_REVIEW = 'StaffCareRecordCreateMedicationReview'
export const API_STAFF_USER_PROFILE = 'StaffUserProfile'